services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  api_gateway:
    build:
      context: .
      dockerfile: apps/api_gateway/Dockerfile
    container_name: api_gateway
    env_file:
      - apps/api_gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  user_service:
    build:
      context: .
      dockerfile: apps/user_service/Dockerfile
    container_name: user_service
    env_file:
      - apps/user_service/.env
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  template_service:
    build:
      context: .
      dockerfile: apps/template_service/Dockerfile
    container_name: template_service
    env_file:
      - apps/template_service/.env
    ports:
      - "3002:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  email_service:
    build:
      context: .
      dockerfile: apps/email_service/Dockerfile
    container_name: email_service
    env_file:
      - apps/email_service/.env
    ports:
      - "3003:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  push_service:
    build:
      context: .
      dockerfile: apps/push_service/Dockerfile
    container_name: push_service
    env_file:
      - apps/push_service/.env
    ports:
      - "3004:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

volumes:
  pgdata:
